### ISSUE TITLE
Display SSH fingerprint when node is created

### ISSUE THREAD

**Issue by jgraef** [sporestack/sporestack-python#4]
Please show the SSH fingerprints of the node after it is created or in node_info.

**Comment by teran-mckinney** [comment]
Hey,

Thanks for contacting. Unfortunately, no way to do this as I can't predict what the fingerprint will be. You might be able to do an ipxe spawn and specify the host key and grab the fingerprint from that. Or put a secret on the server with an install script, grab the secret over SSH, and if it matches add that key.

This can be a bit of a tricky grey area. Do you know of any existing hosts that do this, and how they solved it?

-Teran

**Comment by teran-mckinney** [comment]
I'm going to close this out for now. Please reopen it if you'd like to talk about this further.
