### ISSUE TITLE
docs: clarify bw_per_day

### ISSUE THREAD

**Issue by kewde** [sporestack/sporestack-python#5]
The docs are pretty light on this.
I assume this is bandwidth per day measured in the unit gigabytes?

**Comment by teran-mckinney** [comment]
Yes! Exactly. It's gigabytes per day. I really don't document SporeStack well at all. Would you want to see this in sporestack-python, the limited API documentation section, and/or anywhere else in particular?

**Comment by kewde** [comment]
@teran-mckinney 

Are the docs on GitHub? I wouldn't mind making the edits myself really - makes it easier for you.

**Comment by teran-mckinney** [comment]
Unfortunately not, I'll probably add a section for /options and update those. This would be here: https://sporestack.com/api_documentation

I actually have a V2 API in the works that hopefully will be much better about this. I'll add a quick note there but not invest too much in the current setup unless requested.

**Comment by kewde** [comment]
A bit more of a meta question but I'm plan on writing a provisioning tool for [kontena.io](kontena.io). Basically you'll be able to automatically spawn a Kontena node with SporeStack as the provider. 
Should I make an issue about it here - or is there a way I can document this so SporeStack users know this?

Also the refence code for the implementation is linked below for those interested, it will be at least another 3 months before I get to this task but it's actually quite easy. SporeStack supports passing a `cloudinit` - just like the provider below. Adding SporeStack should be a piece of cake.
https://github.com/kontena/kontena/pull/748/files

Is there perhaps a test environment for sporestack?  I'm pretty sure all I need to do is pass the original cloudinit file as provided by that PR, but if there's another way, I'd rather not purchase a new server for a day each time I fail to deploy.

**Comment by kewde** [comment]
Thanks for addings it to the docs!

**Comment by teran-mckinney** [comment]
Wow, that is really neat. Hmmm...

So the best setup for this would probably be a launch profile: https://github.com/sporestack/node-profiles

Would it fit that design fairly well? I don't think those even support cloudinits, though. I haven't used cloudinit.

Does Kontena have any sort of existing iPXE configuration? The new API will focus primarily on iPXE. And given your 3 months out figure, the V2 API may be the defacto. If you have notable interest in this, I can see about including cloudinit in V2 but a lot of V2s design is in being able to host on my own baremetal, of which I only support iPXE.

I also need to update the node-profiles to V2. V2 isn't even tested yet heavily so still a little ways out.

There's no test environment as of yet but I can help you with developing for use on the platform. I can give you a development token for trying it out. Just send me an email for that closer to the date.

PS: I updated the API docs: https://sporestack.com/api_documentation

**Comment by kewde** [comment]
@teran-mckinney 

Actually - I was thinking of implementing SporeStack into _kontena_ rather than implementing kontena into SporeStack. Kontena has a pretty broad userbase, I think having SporeStack as a plugin there will be more beneficial for your service. As far as I know you'll be the only Bitcoin accepting server provider there.

The current API has a cloudinit field - which I intended to use. 

I have an interest in using SporeStack for all my servers - but I want (dare I say, need) a well integrated cluster manager for my servers.

Here's a plugin example library for AWS, the juicy bits are in this directory:
https://github.com/kontena/kontena-plugin-aws/tree/master/lib/kontena/machine/aws

Kontena _solely_ relies on cloudinit for initializing itself, I would like to keep that for maintainability.
A workaround using CoreOS / RancherOS should allow me to harmonize iPXE and cloudinit.

Once I get to implementing it I will send you an email.

**Comment by kewde** [comment]
```
#!ipxe
# Boot a persistent RancherOS to RAM

# Location of Kernel/Initrd images
set base-url http://releases.rancher.com/os/latest

kernel ${base-url}/vmlinuz rancher.state.dev=LABEL=RANCHER_STATE rancher.state.autoformat=[/dev/sda] rancher.cloud_init.datasources=[url:http://example.com/cloud-config]
initrd ${base-url}/initrd
boot
```

PXE is not an issue.

**Comment by teran-mckinney** [comment]
Sounds great, thank you! Definitely curious to talk more about this over email when you have the time.
